CREATE DATABASE IF NOT EXISTS quanly_dotot_nghiep;
USE quanly_dotot_nghiep;

CREATE TABLE SinhVien (
    MaSV VARCHAR(20) PRIMARY KEY,
    HoTen VARCHAR(255) NOT NULL,
    Email VARCHAR(255),
    Lop VARCHAR(50),
    Password VARCHAR(255),
    Token VARCHAR(255)
);

CREATE TABLE DeTai (
    MaDeTai INT PRIMARY KEY AUTO_INCREMENT,
    TenDeTai VARCHAR(255) NOT NULL,
    MoTa TEXT,
    GiangVienHuongDan VARCHAR(255),
    SoLuongToiDa INT DEFAULT 1
);

CREATE TABLE DangKy (
    MaDangKy INT PRIMARY KEY AUTO_INCREMENT,
    MaSV VARCHAR(20) NOT NULL,
    MaDeTai INT NOT NULL,
    NgayDangKy DATETIME DEFAULT CURRENT_TIMESTAMP,
    TrangThai VARCHAR(50) DEFAULT 'Cho duyet',
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
    FOREIGN KEY (MaDeTai) REFERENCES DeTai(MaDeTai)
);